### ISSUE TITLE
请教一下问题

### ISSUE THREAD

**Issue by foreverlms** [versionzhang/python_12306#10]
# 1.需要自己注册那个ruokuai打码平台吗？
# 2. 填写发件人邮箱是什么？感觉可以只填写收件人邮箱，统一由一个邮箱进行发送和，不用填密码了。

**Comment by versionzhang** [comment]
需要自动打码的话就需要自己注册打码平台的账号使用.

邮箱通知是通过登录发件人邮箱使用smtp协议进行发送的,统一一个邮箱会有问题, 由于这个是开源项目,这里的发件人邮箱密码是被所有人看到的,如果在你使用过程中这个邮箱被别人改了密码会导致发送失败.为了更灵活所以采用使用人手动配置邮箱密码发送

**Comment by foreverlms** [comment]
@versionzhang 谢谢解答
