### ISSUE TITLE
若快识别不了验证码，还浪费我充钱

### ISSUE THREAD

**Issue by legolas-zeng** [versionzhang/python_12306#15]
获取车站信息成功
                        正在为您登录
                        使用若快进行验证码识别
                        验证码校验结果: {'result_message': '验证码校验成功', 'result_code': '4'}
                        密码输入错误。如果输错次数超过4次，用户将被锁定。
                        登录失败, 重试1次
                        正在为您登录
                        使用若快进行验证码识别
                        验证码校验结果: {'result_message': '验证码校验成功', 'result_code': '4'}
                        密码输入错误。如果输错次数超过4次，用户将被锁定。
                        登录失败, 重试2次
                        正在为您登录
                        使用若快进行验证码识别
                        验证码校验结果: {'result_message': '验证码校验失败', 'result_code': '5'}
                        验证码识别失败
                        验证码校验失败

                        登录失败, 重试3次
                        正在为您登录
                        使用若快进行验证码识别
                        验证码校验结果: {'result_message': '验证码校验成功', 'result_code': '4'}
                        密码输入错误。如果输错次数超过4次，用户将被锁定。
                        登录失败, 重试4次
                        正在为您登录
                        使用若快进行验证码识别
                        验证码校验结果: {'result_message': '验证码校验成功', 'result_code': '4'}
                        密码输入错误。如果输错次数超过4次，用户将被锁定。
                        登录失败, 重试5次
                        正在为您登录
                        使用若快进行验证码识别
                        验证码校验结果: {'result_message': '验证码校验成功', 'result_code': '4'}
                        您的用户已经被锁定,锁定时间为20 分钟,请稍后再试。
                        重试次数已经超过设置

**Comment by versionzhang** [comment]
看到log信息提示的是你的密码不正确,
`密码输入错误。如果输错次数超过4次，用户将被锁定。`
若快的识别信息是否成功在log中返回为
`验证码校验结果: {'result_message': '验证码校验成功', 'result_code': '4'}`
如果返回成功证明验证码识别成功,返回失败会重试识别验证码不会提交用户登录

请检查一下你的12306的用户名密码是否配置正确, 谢谢

**Comment by versionzhang** [comment]
没有后续反馈暂时先关闭issue
