### ISSUE TITLE
用`img.save()`代替`img.show()`吧

### ISSUE THREAD

**Issue by edsion1107** [versionzhang/python_12306#16]
https://github.com/versionzhang/python_12306/blob/d3d876bdc869855d8daecf34b54f40c17883f77f/python12306/logic/login/captcha.py#L190

放在服务器上运行这个代码，看不到图片的～改成存一个本地文件，然后可以自己手动拉回来看

**Comment by versionzhang** [comment]
我加一个配置项吧，如果开启的话，就保存在当前文件夹内，如果不开启的话就直接显示出来

**Comment by versionzhang** [comment]
配置项已经添加
