### ISSUE TITLE
使用server酱代替邮件通知

### ISSUE THREAD

**Issue by edsion1107** [versionzhang/python_12306#17]
https://github.com/versionzhang/python_12306/blob/d3d876bdc869855d8daecf34b54f40c17883f77f/python12306/scheduler.py#L142

用这个比邮件通知配置起来简单些。
http://sc.ftqq.com/3.version

**Comment by versionzhang** [comment]
明天看有没时间加一下

**Comment by versionzhang** [comment]
已经添加使用server酱服务的微信通知
