### ISSUE TITLE
查询到符合条件的车次与的的配置文件不一样

### ISSUE THREAD

**Issue by pengning** [versionzhang/python_12306#18]
这个是配置文件内容
presale_enable: True
presale_config:
  # 预售日期, 单日期,与正常模式的配置不同,请注意
  travel_date: "2019-02-03"

  # 预售模式下查询余票时间间隔 单位秒
  query_left_ticket_time: 1
  # 预售模式下提前多久停止正常模式的查询只查询预售模式的日期的票, 单位分钟
  stop_time: 2
  # 预售模式下持续时间,过了持续时间之后,变为正常查询,按照正常查询的模式, 单位分钟
  continue_time: 15
  # 预售时间点, 可以为多个, 格式如下所示
  # "%H:%M" 小时:分钟
  start_times:
    - "20:00"
    - "21:00"

basic_config:
  # 快速下单接口, True or False, 目前12306的web端使用的是正常下单接口,快速下单是从
  # testerSunshine 12306的流程中拿到的,测试过程中发现有时候会出票失败, 暂时正常下单流程是稳定的
  fast_submit: False
  # 调试模式, True or False, True为调试模式,终端会输出调试信息,False为正常模式,只显示必要信息
  debug: False

  # 出发日期(list)，格式ex：
    # - 2019-01-26
    # - 2019-01-27
  travel_dates:
    # 已经更新为多日期
    - "2019-02-03"

  ticket_type:
    # 目前取值有两种
    # 成人票或者学生票
    # 暂时未考虑学生票和成人票混合的情况
    "成人票"

  # 是否根据时间范围 和 乘车类型 购票
  # 否则将需要手动填写车次
  manual_trainnum_enable: False

  # 列车类型: 高铁 G 动车 D 普快K, 特快T, C城际 Z 直达 L 临客 普通纯数字车次 用S代替
  # manual_trainnum_enable 选项为 False时有效
  # train_types: [G,D,K,T]
  train_types: [G]

  # 可接受最早出发时间 格式ex：
  # manual_trainnum_enable 选项为 False时有效
  earliest_time: "20:00"

  # 可接受最晚抵达时间 格式ex：
  # manual_trainnum_enable 选项为 False时有效
  latest_time: "24:00"
这个是日志内容：
[2019-01-19 20:22:32] INFO - 查找到符合配置的车次信息: G1778,G502
查找到符合配置的2个车次都是上午七点多的，而我配置文件的是要晚上八点多和九点多的。请问是什么原因呢？

**Comment by versionzhang** [comment]
你好，你这边可以提供一下出发站和到达站的信息吗

**Comment by versionzhang** [comment]
找到问题了，这里是显示问题，显示的是有票的车次过滤席位信息之后的车次信息，还未按时间和类型过滤车次，实际上不影响最后过滤后的结果

**Comment by versionzhang** [comment]
已修复

**Comment by pengning** [comment]
好的！谢谢！
