### ISSUE TITLE
感觉无效啊，，，每次查个几次就报错了，去12306看明明有很多票。。

### ISSUE THREAD

**Issue by liwendian** [versionzhang/python_12306#20]
难道是打开的方式不对？还有，这个会不会收集个人信息？？？

**Comment by liwendian** [comment]
比如：
[32m当次查询时间间隔为 4.93 秒, 查询请求处理时间 1.6 秒[39m
                        [32m用户状态检测:未到检测时间[39m
                        [32m查询第 2 次[39m
                        [32m当前查询日期为 **2019-02-19** 出发地 **徐州** 目的地 **上海**[39m
                        [32m当前正在使用CDN IP 为34.233.67.34[39m
[31m
'content-type'
[39m
                        [32m日期 **2019-02-19** 出发地 **徐州** 目的地 **上海** 满足条件的车次暂无余票, 正在重新查询[39m
                        [32m当次查询时间间隔为 4.34 秒, 查询请求处理时间 0.386 秒[39m

**Comment by liwendian** [comment]
关了CDN就好了。。。。

**Comment by versionzhang** [comment]
代码是开源的，除了自动打码和模拟12306交互其他没有别的网络请求。个人信息配置都是保存在本地的。你可以看下源码，所有的逻辑都在里面。
cdn的这个问题还没有好的方法解决，这个列表是从网上搜集的，所以可用性不可知。。稳妥起见先不要开cdn吧，我还在看有没有好的解决方法

**Comment by liwendian** [comment]
谢谢，start
