### ISSUE TITLE
返回状态码有问题302

### ISSUE THREAD

**Issue by ghost** [versionzhang/python_12306#24]
https://kyfw.12306.cn/otn/leftTicket/queryZ?leftTicketDTO.train_date=2019-03-14&leftTicketDTO.from_station=HFH&leftTicketDTO.to_station=SHH&purpose_codes=ADULT
302
返回状态码有问题

**Comment by ghost** [comment]
302定义
302 redirect: 302 代表暂时性转移(Temporarily Moved )。
意思就是你访问网址A，但是网址A因为服务器端的拦截器或者其他后端代码处理的原因，会被重定向到网址B。

不知道是不是12306拦截了有某个关键词的访问请求。

**Comment by versionzhang** [comment]
我看了一下发现是查询余票的url变成了 `leftTicket/queryX`, 看看近段时间有没有空加上自动检测查询余票端口的功能

**Comment by versionzhang** [comment]
已经添加了变更余票查询端口的功能
