### ISSUE TITLE
接口错误

### ISSUE THREAD

**Issue by GZKY-PY** [versionzhang/python_12306#26]
验证码校验结果: {'result_message': '验证码校验成功', 'result_code': '4'}
 登录接口提交返回数据出现问题
登录失败, 重试1次
登录接口返回的数据有错误
如何解决

**Comment by versionzhang** [comment]
这个问题我也遇到了,加了设备识别码之后感觉还是频繁失败,还在查具体原因

**Comment by GZKY-PY** [comment]
哈 本来清明节想尝试能不能抢到票的嘿嘿

**Comment by GZKY-PY** [comment]
作者 应该是headers的问题 我又检查的一遍 post的url是没错的, 但是好想referer有变化 但是换了一下也不行
你怎么看?

**Comment by versionzhang** [comment]
我改了加了一个新的分支,现在采用selenium来完整获取cookie,感觉登录成功的概率提高不少了. 不过需要简单配置一下selenium, 代码里面采用的是chrome driver,你可以试一下
后面的下单流程貌似没怎么检测,感觉只是检测了登录的流程.下单的流程还是能正常走通.
分支名称为change_cookies

**Comment by GZKY-PY** [comment]
作者 我好像看出问题所在了 可以改用验证验证码是否成功的接口
urllib.parse.urlencode({
    "answer": 坐标,
    "rand": "sjrand",
    "login_site": "E",
}).encode('utf-8')
这种方法可以过去 
有几种验证 这种比较稳定

**Comment by versionzhang** [comment]
这个登录不成功是因为12306加了设备指纹验证,不是验证码识别不正确导致的..
现在的问题在于怎么解决cookie里面的两个设备指纹的两个字段RAIL_EXPIRATION和RAIL_DEVICEID..
没有这两个字段的话是没办法登录成功的.

**Comment by GZKY-PY** [comment]
好像出来的cookie是少了这两个字段,那么只能selenium换取cookie了吗?这样一来可就慢多了

**Comment by GZKY-PY** [comment]
刚才试了下selenium获取关键字段的版本 也登录不进去啊

**Comment by versionzhang** [comment]
看看打印的信息里面有没有`已经获取设备指纹`这一条,如果有的话,一般都是能登录成功的.
获取设备指纹是不请求验证码识别的,只是通过浏览器完全的获取cookie.
拿到了那两个字段就才会去识别验证码.我试了几次都是可以登录成功的.
如果获取设备指纹成功,但是后面的请求出错了,可以换一下网络环境,比如用热点什么的再试一下.
如果还不行,就把一些出错的log信息贴上来,我来定位一下

**Comment by GZKY-PY** [comment]
就是很大几率获取不到设备ID 只能访问主页才能拿到ID吗?

**Comment by GZKY-PY** [comment]
代理ip也是不行的 十分之一的成功率

**Comment by GZKY-PY** [comment]
代理ip也是不行的 十分之一的成功率

**Comment by GZKY-PY** [comment]
试了好几遍 好不容易进去一次 然后
当前查询日期为 **2019-03-30** 出发地 **广州** 目的地 **潮汕**
                        日期 **2019-03-30** 出发地 **广州** 目的地 **潮汕** 满足条件的车次暂无余票, 正在重新查询
                        当次查询时间间隔为 4.74 秒, 查询请求处理时间 0.619 秒
                        用户状态检测:未到检测时间
                        查询第 12 次
                        当前查询日期为 **2019-03-30** 出发地 **广州** 目的地 **潮汕**
                        日期 **2019-03-30** 出发地 **广州** 目的地 **潮汕** 满足条件的车次暂无余票, 正在重新查询
                        当次查询时间间隔为 4.1 秒, 查询请求处理时间 0.59 秒
                        用户状态检测:未到检测时间
                        查询第 13 次
                        当前查询日期为 **2019-03-30** 出发地 **广州** 目的地 **潮汕**
                        日期 **2019-03-30** 出发地 **广州** 目的地 **潮汕** 满足条件的车次暂无余票, 正在重新查询
浏览器查询有票啊  但是它一直在重新请求

**Comment by versionzhang** [comment]
我刚试了下,3.30号广州到潮汕的二等座票是可以的查到购买的..
你看下你的坐席和时间段和其他什么相关设置有没问题..

这个登录问题我也头大,摸不着到底什么情况能拿到那两个设备指纹.我再看看吧..
目前就先用selenium这个方法吧..后面看有没其他的好的方法..

**Comment by GZKY-PY** [comment]
我输出了所有的debug 都是有返回值的 但是查询不到票 也无法自动下单 是个啥情况

**Comment by versionzhang** [comment]
你看一下查询余票的接口的返回数据,这块查票购票的逻辑应该没变,就是查询的url从`queryZ`变成了`query`,

``` 
[2019-04-01 09:13:41] DEBUG - https://kyfw.12306.cn/otn/leftTicket/query Get 参数 leftTicketDTO.train_date=2019-04-02&leftTicketDTO.from_station=GZQ&leftTicketDTO.to_station=CBQ&purpose_codes=ADULT
```

看一下日志里面这条请求的返回值有没有正常返回数据,如果有正常返回的话,看一下你的配置文件的相关配置项有没有问题.如果没有返回数据的话那就可能12306暂时限制了你的查票..

我重新跑了一遍流程,从登录到购票完成发送通知都是能正常走通的,你再debug一下吧..如果还找不到问题,可以把关键日志信息粘贴上来(注意删除log里面的个人信息)

```
[2019-04-01 09:13:58] INFO - 提交订单成功, 订单号为 EA33621860, 请登录12036在30分钟内完成支付
[2019-04-01 09:13:58] DEBUG - 请求 url https://kyfw.12306.cn/otn/queryOrder/queryMyOrderNoComplete
[2019-04-01 09:13:58] DEBUG - https://kyfw.12306.cn/otn/queryOrder/queryMyOrderNoComplete Post 参数 {'_json_att': ''}
[2019-04-01 09:13:58] DEBUG - 返回response url https://kyfw.12306.cn/otn/queryOrder/queryMyOrderNoComplete
[2019-04-01 09:13:58] DEBUG - https://kyfw.12306.cn/otn/queryOrder/queryMyOrderNoComplete 返回值 {XXXXjson返回值(移除个人信息)}
[2019-04-01 09:14:00] INFO - 当次查询时间间隔为 2.14 秒, 查询请求处理时间 17.7 秒
[2019-04-01 09:14:00] INFO - 抢票成功，你已开启邮箱配置，稍后会收到邮件通知
[2019-04-01 09:14:00] INFO - 车票信息：
[2019-04-01 09:14:00] INFO - 未开启微信通知
[2019-04-01 09:14:03] INFO - 邮件发送成功
```

**Comment by versionzhang** [comment]
> 好像出来的cookie是少了这两个字段,那么只能selenium换取cookie了吗?这样一来可就慢多了

刚刚优化了一下,获取设备指纹之后缓存到本地的pickle文件,就不用重新再次获取了,验证过缓存之后的设备指纹还是可以使用的.这个缓存设置的是24小时,如果需要重新获取,删除掉`device_pickle.pickle`这个文件就可以了,目前暂时还没仔细测试,等测试完成之后合并到主分支

**Comment by GZKY-PY** [comment]
对 利用cookie需要参数 的过期时间做优化  可以的 感谢大佬

**Comment by GZKY-PY** [comment]
但是如今快若平台好像已经挂掉了

**Comment by versionzhang** [comment]
是的，12306也添加了候补购票，这个项目应该不再维护了。。
